// Default
#define CONFIG_PROJECT_CODE "litncov"
#define CONFIG_DEVICE_FW 0.4
#define CONFIG_WIFI_RETRY_TIME 10

// USER
#define CONFIG_LIT_HEALTH_USER ""
#define CONFIG_LIT_HEALTH_PWD ""
#define CONFIG_SERVERCHAN_SCKEY ""

// TASK
#define CONFIG_LIT_REPORT_TIME "17:04:00"